export enum Anchor {
  CENTROID = 'CENTROID',
  TOP_CENTER = 'TOP_CENTER',
  UPPER_CENTER = 'UPPER_CENTER',
  BOTTOM_CENTER = 'BOTTOM_CENTER',
  LOWER_CENTER = 'LOWER_CENTER',
  RIGHT_CENTER = 'RIGHT_CENTER',
  LEFT_CENTER = 'LEFT_CENTER',
}
